baseURL: "https://notes.kraker.dev/"
#languageCode: "en-us"
title: "Alex's Second Brain (AKA Zettelkasten)"
theme: "book"


#outputs:
#  home: [ "HTML", "RSS", "JSON" ]

contentDir: second-brain
uglyRLs: true
enableGitInfo: true

params:
  bookTheme: "auto"
  bookComments: false
#
#minify:
#  disableCSS: false
#  disableHTML: false
#  disableJS: false
#  disableJSON: false
#  disableSVG: false
#  disableXML: false
#  minifyOutput: false
