---
# Hugo notes.kraker.dev site config

baseURL: "https://notes.kraker.dev/"
languageCode: "en-us"
title: "Alex's Second Brain (AKA Zettelkasten)"
theme: "book"


#outputs:
#  home: [ "HTML", "RSS", "JSON" ]

contentDir: second-brain
uglyRLs: true
enableGitInfo: true

params:
  BookTheme: "auto"
  BookComments: false
  BookToC: true
  #BookSection: '*'
