---
# Hugo notes.kraker.dev site config

baseURL: "https://notes.kraker.dev/"
languageCode: "en-us"
title: "Alex's Second Brain"
theme: "book"

contentDir: second-brain
uglyurls: true

params:
  BookTheme: "auto"
  BookComments: false
  BookToC: true
  #BookSection: '*'
